name: CI/CD do Marketplace Django

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Construir imagem Docker
        run: docker build -t marketplace-django-app .

      - name: Formatar o código com Black
        run: docker run --rm -v ${{ github.workspace }}:/app -w /app marketplace-django-app black --check .
   
      - name: Análise de Segurança Estática
        run: docker run --rm -v ${{ github.workspace }}:/app -w /app marketplace-django-app bandit -f json -o bandit_report.json .
        continue-on-error: true

      - name: Lint de Templates Django com djhtml
        run: docker run --rm -v ${{ github.workspace }}:/app -w /app marketplace-django-app djhtml --check .

      - name: Checar migrations pendentes
        run: docker run --rm -v ${{ github.workspace }}:/app -w /app marketplace-django-app python manage.py makemigrations --check --dry-run

      - name: Rodar testes com coverage
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app marketplace-django-app coverage run manage.py test
          docker run --rm -v ${{ github.workspace }}:/app -w /app marketplace-django-app coverage report

      - name: Gerar relatório de cobertura em HTML
        run: docker run --rm -v ${{ github.workspace }}:/app -w /app marketplace-django-app coverage html
        
      - name: Publicar HTML do coverage como artefato
        uses: actions/upload-artifact@v4
        with:
          name: cobertura-html
          path: htmlcov/
